### ISSUE TITLE
Noms d'algunes variables

### ISSUE THREAD

**Issue by svilaa** [Termeni/ChallengeAccepted_Server#24]
Les següents variables tindrien de tenir millors noms, per exemple:

A User:

     private Set challengeUsers = new HashSet(0);
     private Set valorationsForIdUser = new HashSet(0);
     private Set valorationsForIdValorator = new HashSet(0);

A Challenge:

     private Set challengeUsers = new HashSet(0);
     private Set challengeTags = new HashSet(0);

**Comment by Termeni** [comment]
Miro de regenerar-ho tot amb hibernate a vere si puc sense que peti tot.
