### ISSUE TITLE
Mapping d'Hibernate

### ISSUE THREAD

**Issue by svilaa** [Termeni/ChallengeAccepted_Server#25]
Alguns Sets que genera diria que sobren:

A Tag:

     private int id;
     private String tag;
     private Set challengeTags = new HashSet(0);

challengeTags no està contemplat a la base de dades.

A User per exemple si que pot ser útil:

    private Set valorationsForIdUser = new HashSet(0);
    private Set valorationsForIdValorator = new HashSet(0);

Pero:      

    private Set challengeUsers = new HashSet(0);

Aquí entenc que el nom està mal, es guarden els reptes on ha participat l'usuari, està bé, però challengeUsers és molt confús.

A Score:

    private Set users = new HashSet(0);

Quin ús té users?

**Comment by Termeni** [comment]
Son les relacions inverses que ha generat hibernate de forma automaitca suda de la majoria.
