### ISSUE TITLE
Bug in SignUp

### ISSUE THREAD

**Issue by svilaa** [Termeni/ChallengeAccepted_Server#34]
The second findUserByEmail is incorrect, must be findUserByName.

User searchedUser = userHelper.findUserByEmail(user.getEmail());
if(searchedUser!=null){
    throw new ExistingUserEmailException();
}
searchedUser = userHelper.findUserByEmail(user.getEmail());
if(searchedUser!=null){
    throw new ExistingUsernameException();
}

**Comment by Termeni** [comment]
sip ho havia de canviar pero va petar el merge de deu i vaig sudar ara ho apañare
