### ISSUE TITLE
Objecte o id?

### ISSUE THREAD

**Issue by svilaa** [Termeni/ChallengeAccepted_Server#35]
Per exemple, a ChallengeUser, tal qual ho genera Hibernate és correcte? O s'hauria de canviar per a que sigui equivalent a la base de dades utilitzant els IDs?

     private int id;
     private Challenge challenge;
     private User user;

**Comment by Termeni** [comment]
Millor ids que no men acabo de fiar de hibernate per aixo, segurament esitugi bé també pero com que es de les primeres vegades que ho configuro de 0 millor anar amb Id's
