### ISSUE TITLE
Crear dos taules de localització, una pels usuaris i una altra pels reptes

### ISSUE THREAD

**Issue by svilaa** [Termeni/ChallengeAccepted_Server#43]
A l'hora d'obtenir les localitzacions properes, s'obtenen tant d'usuaris com de reptes, això fa que després s'hagi de comprovar cada id per veure si correspon a un repte o a un usuari.
Només es modificaria el lloc on es guarden, la classe Location seguiria com està.
De moment ho he deixat en comentaris, ara només s'imprimeixen els ids que s'han trobat, però un cop arreglat això, la funció per obtenir reptes ja retornaria les dades correctament.

**Comment by svilaa** [comment]
Tot i així, demà provaré de modificar la query per a que comprovi si es tracta d'un repte o d'un usuari.

**Comment by Termeni** [comment]
No crec que faci falta amb la taula localitzacio en tenim de sobres despres per SQL es un moment veure si correspona un usuari o a un reto

**Comment by svilaa** [comment]
Ja funciona. Igualant els IDs de localització amb els dels reptes ha funcionat.
